// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csvgqzlsrvzvummsdjqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzdmdxemxzcnZ6dnVtbXNkanF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMTcwMTgsImV4cCI6MjA2MDc5MzAxOH0.TKe1qY2RQhrtfg9neAQ1JEhK5BkXCzrbnbQp5vxn6kE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);